add same stuff for scope-manager snapshots

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -363,6 +363,43 @@ jobs:
             exit 1
           fi
 
+  scope_manager_snapshots_clean:
+    name: Verify scope-manager snapshots are clean
+    environment: ${{ (github.repository == 'typescript-eslint/typescript-eslint' && github.ref == 'refs/heads/main') && 'main' || '' }} # Have to specify per job
+    needs: [build, affected-for-tests]
+    if: ${{ contains(fromJson(needs['affected-for-tests'].outputs.unit_tests_packages), 'scope-manager') }}
+    runs-on: ubuntu-latest
+    env:
+      NX_CI_EXECUTION_ENV: 'ubuntu-latest'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
+        with:
+          persist-credentials: false
+      - name: Install
+        uses: ./.github/actions/prepare-install
+        with:
+          node-version: ${{ env.PRIMARY_NODE_VERSION }}
+      - name: Build
+        uses: ./.github/actions/prepare-build
+
+      - name: Delete all scope-manager fixture snapshots
+        run: pnpm exec nx run scope-manager:clean-fixtures
+
+      - name: Regenerate scope-manager fixture snapshots
+        run: pnpm exec nx test scope-manager -u
+        env:
+          CI: true
+
+      - name: Fail if regenerating snapshots produced a diff
+        run: |
+          changes="$(git status --porcelain -- packages/scope-manager/tests/fixtures)"
+          if [ -n "$changes" ]; then
+            echo "$changes"
+            echo "::error::Regenerating scope-manager fixture snapshots from scratch produced a different set of files than what is committed. This means some snapshot files are stale/orphaned/missing in git. Run 'pnpm exec nx run scope-manager:clean-fixtures && pnpm exec nx test scope-manager' locally and commit the resulting changes."
+            exit 1
+          fi
+
   plugin_unit_tests:
     # Note -- intentionally use the same name as unit_tests just so everything looks uniform in the checks section
     name: Run Unit Tests
@@ -545,6 +582,7 @@ jobs:
       - stylelint
       - integration_tests
       - ast_spec_snapshots_clean
+      - scope_manager_snapshots_clean
       - plugin_unit_tests
       - unit_tests
       - unit_tests_project_service
